// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6C3cjyV61_ElI_kXQubGXf4p90GspUKw',
    appId: '1:101837455423:web:598d9dbecb0ec2004b388a',
    messagingSenderId: '101837455423',
    projectId: 'sigecor-f14fb',
    authDomain: 'sigecor-f14fb.firebaseapp.com',
    storageBucket: 'sigecor-f14fb.firebasestorage.app',
    measurementId: 'G-3VXSRV8W6W',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLCg4TLKrSltRhH0XcB8qwNNh0_8nfbg4',
    appId: '1:101837455423:ios:62be06810be794ee4b388a',
    messagingSenderId: '101837455423',
    projectId: 'sigecor-f14fb',
    storageBucket: 'sigecor-f14fb.firebasestorage.app',
    iosBundleId: 'com.example.sistemaDeReservas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLCg4TLKrSltRhH0XcB8qwNNh0_8nfbg4',
    appId: '1:101837455423:ios:62be06810be794ee4b388a',
    messagingSenderId: '101837455423',
    projectId: 'sigecor-f14fb',
    storageBucket: 'sigecor-f14fb.firebasestorage.app',
    iosBundleId: 'com.example.sistemaDeReservas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6C3cjyV61_ElI_kXQubGXf4p90GspUKw',
    appId: '1:101837455423:web:575638499be6c2274b388a',
    messagingSenderId: '101837455423',
    projectId: 'sigecor-f14fb',
    authDomain: 'sigecor-f14fb.firebaseapp.com',
    storageBucket: 'sigecor-f14fb.firebasestorage.app',
    measurementId: 'G-2YY6H407MZ',
  );
}
