name: Flutter Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Crear local.properties
        run: |
          echo "flutter.sdk=$(which flutter | sed 's/\/bin\/flutter//')" > android/local.properties

      - name: Instalar dependencias
        run: flutter pub get

      - name: Decodificar keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-keystore.jks

      - name: Crear key.properties
        run: |
          cat > android/key.properties << EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=release-keystore.jks
          EOF

      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Build AAB
        run: flutter build appbundle --release --android-skip-build-dependency-validation

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          name: "Release ${{ github.ref_name }}"
          body: |
            ## Release ${{ github.ref_name }}
            - APK para instalacion directa
            - AAB para Google Play Store